# Generated by Django 5.0.6 on 2024-07-10 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('productadmin', '0002_productvariant_is_featured'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='order_status',
            field=models.CharField(choices=[('Order Pending', 'Order Pending'), ('Order Confirmed', 'Order Confirmed'), ('Order Shipped', 'Order Order Shipped'), ('Order Delivered', 'Order Delivered')], default='Order Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='id',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productadmin.productvariant')),
                ('user', models.ForeignKey(limit_choices_to={'is_product_admin': False, 'is_superuser': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
