# Generated by Django 5.0 on 2024-06-21 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_userprofile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
