# Generated by Django 5.0.6 on 2024-07-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
