# Generated by Django 5.0.6 on 2024-07-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productadmin', '0002_productvariant_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
