# Generated by Django 5.0.6 on 2024-07-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productadmin', '0003_productvariant_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='category-image'),
        ),
        migrations.AlterField(
            model_name='colorimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='colorImg'),
        ),
    ]
