# Generated by Django 5.0.2 on 2024-07-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productadmin', '0004_alter_category_image_alter_colorimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorimage',
            name='image',
            field=models.ImageField(upload_to='colorImg'),
        ),
    ]
