# Generated by Django 5.0.2 on 2024-07-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productadmin', '0005_alter_colorimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='colorImg'),
        ),
    ]
