# Generated by Django 5.0.2 on 2024-07-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productadmin', '0007_remove_color_images_color_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='product_status',
            field=models.CharField(choices=[('Sale', 'Sale'), ('Out of Stock', 'Out of Stock')], default='Sale', max_length=20),
        ),
    ]
