# Generated by Django 5.0.6 on 2024-07-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productadmin', '0008_productvariant_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='image',
        ),
        migrations.AddField(
            model_name='color',
            name='images',
            field=models.ManyToManyField(related_name='colors', to='productadmin.colorimage'),
        ),
    ]
